### ISSUE TITLE
Bulb Switcher III

### ISSUE THREAD

**Issue by riddhi-jain** [riddhi-jain/DSAready#24]
There is a room with n bulbs, numbered from 1 to n, arranged in a row from left to right. Initially, all the bulbs are turned off.

At moment k (for k from 0 to n - 1), we turn on the light[k] bulb. A bulb change color to blue only if it is on and all the previous bulbs (to the left) are turned on too.

Return the number of moments in which all turned on bulbs are blue.

 Example:
Input: light = [3,2,4,1,5]
Output: 2
Explanation: All bulbs turned on, are blue at the moment 3, and 4 (index-0).

**Comment by Rameshchandrapola** [comment]
Hey!
can I send a code for this question?
