### ISSUE TITLE
cannot be cloned

### ISSUE THREAD

**Issue by jas-karan** [riddhi-jain/DSAready#5]
Hi, I want to contribute to this repository. But when I tried to clone it to my system, It showed an error

## error: invalid path 'Arrays/Count More Than n\k Occurances.cpp'

maybe this is because of naming of the above file.
#### We can try changing the name.

**Comment by riddhi-jain** [comment]
Hey @jas-karan ! The name of above file has been fixed.
Your contribution is most welcome :)
